import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useGetLeaderboardQuery } from "../services/valorant";
import PlayerCard from "../components/molecules/playerCard";
import { Container } from "@mantine/core";
import Spinner from "../components/atoms/spinner";

const ITEMS_PER_PAGE = 1000;

const Home: NextPage = () => {
  const [page, setPage] = useState(1);
  const [isLoadingMore, setIsLoadingMore] = useState(false);
  const region = "eu";
  const { data, isLoading, isError } = useGetLeaderboardQuery({
    version: "v2",
    region: region,
  });

  const handleScroll = () => {
    const distanceToBottom =
      document.documentElement.offsetHeight -
      (window.innerHeight + window.scrollY);

    if (distanceToBottom < 100 && !isLoadingMore) {
      loadMoreData();
    }
  };
  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const loadMoreData = () => {
    setPage((prevPage) => prevPage + 1);
    setIsLoadingMore(true);
  };

  if (isLoading) {
    return <Spinner />;
  }

  if (isError) {
    return <div>Error occurred while fetching data</div>;
  }

  const endIndex = page * ITEMS_PER_PAGE;
  const loadedPlayers = data?.players.slice(0, endIndex);

  return (
    <div className={styles.container}>
      <Head>
        <title>VOID: Valorant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container size="sm" style={{ margin: "auto" }}>
          {loadedPlayers?.map((playerData, index) => (
            <PlayerCard
              key={`${"1839"}-${index}`}
              data={playerData}
              region={region}
            />
          ))}
        </Container>
      </main>
    </div>
  );
};

export default Home;
